name: Post JSON File to Two URLs

on:
  push:
    branches:
      - main  # Runs only when pushing to the main branch
  workflow_dispatch:  # Allows manual trigger

jobs:
  post_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Send JSON Data to First URL
        run: |
          curl -X POST "https://:TYfLfsPcRrSbgOxMpb8UWw@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:At0H2kt_Q6qCtU1KToBTrQ/streams/AQAAAHqT-0vq-UfKrYhiuh1lTPcAAAAA" \
               -H "Content-Type: application/json" \
               -d @stream.json

      - name: Send JSON Data to Second URL
        run: |
          curl -X POST "https://:lTivunzhTtqlO04FwathZA@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:At0H2kt_Q6qCtU1KToBTrQ/streams/AQAAAPLnBKVYnEy9sSavssQrC2YAAAAA" \
               -H "Content-Type: application/json" \
               -d @stream.json

